spring:
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
    timeout: 1000
  profiles:
    active: common

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/

logging:
  config: classpath:log4j2.xml

feign:
  hystrix:
    enabled: true