spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/smart_njupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: ${jdbc.driver-class-name}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
    timeout: 1000
  profiles:
    active: common

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.njupt.*.pojo.entity,

logging:
  config: classpath:log4j2.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/
feign:
  hystrix:
    enabled: true
